// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkvqzujckeigjlxklsyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrdnF6dWpja2VpZ2pseGtsc3lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTczNzQsImV4cCI6MjA2MTA5MzM3NH0.Ew74z5F1p5tFMnoQaebMAocvLfmnjrBNSTUhDoSk4Ck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);